// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCrEA8zGeEw_PJxEYsEoX8V9AtZhS0xmKE',
    appId: '1:365115959049:web:8b884ccd6d9a81d3fa15d8',
    messagingSenderId: '365115959049',
    projectId: 'test-firebase-ppb',
    authDomain: 'test-firebase-ppb.firebaseapp.com',
    storageBucket: 'test-firebase-ppb.firebasestorage.app',
    measurementId: 'G-DVB29XK1FV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBAnpmlTqRORRwxMbkb6GSZ8AZJykC_s7Q',
    appId: '1:365115959049:android:a91d17109a1ec623fa15d8',
    messagingSenderId: '365115959049',
    projectId: 'test-firebase-ppb',
    storageBucket: 'test-firebase-ppb.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAryLl_1caypunVq-b7w-P20SqiyV3mkGI',
    appId: '1:365115959049:ios:1d257e7e1f52d411fa15d8',
    messagingSenderId: '365115959049',
    projectId: 'test-firebase-ppb',
    storageBucket: 'test-firebase-ppb.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAryLl_1caypunVq-b7w-P20SqiyV3mkGI',
    appId: '1:365115959049:ios:1d257e7e1f52d411fa15d8',
    messagingSenderId: '365115959049',
    projectId: 'test-firebase-ppb',
    storageBucket: 'test-firebase-ppb.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCrEA8zGeEw_PJxEYsEoX8V9AtZhS0xmKE',
    appId: '1:365115959049:web:bdf1ee7bfc1896e2fa15d8',
    messagingSenderId: '365115959049',
    projectId: 'test-firebase-ppb',
    authDomain: 'test-firebase-ppb.firebaseapp.com',
    storageBucket: 'test-firebase-ppb.firebasestorage.app',
    measurementId: 'G-01C1WD66GL',
  );

}